server:
 port: 8888
 
spring:
 cloud:
   config:
     server:
      git:
       uri: https://github.com/fran86alcalde/bootcamp-configserver
       default-label: main
       search-paths:
       - '*service'